# 🚀 Day 7 — NumPy
## AI/ML Engineer Bootcamp

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.5.1


In [2]:
# Create a 1D NumPy array

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
# Create a 1D NumPy array

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
# Create a 2D array

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [5]:
# Create zeros, ones and full arrays

print(np.zeros(5))
print(np.ones(5))
print(np.full((2, 3), 7))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[7 7 7]
 [7 7 7]]


In [7]:
# Create sequences using arange and linspace

print("arange:", np.arange(1, 11, 2))
print("linspace:", np.linspace(0, 10, 5))

arange: [1 3 5 7 9]
linspace: [ 0.   2.5  5.   7.5 10. ]


In [8]:
# Check array properties

print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Data Type:", arr_2d.dtype)

Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64


In [9]:
# Access array elements using indexing

print("First:", arr[0])
print("Third:", arr[2])
print("Last:", arr[-1])

First: 10
Third: 30
Last: 50


In [12]:
# Extract part of an array
print(arr)
print(arr[1:4])
print(arr[:3])
print(arr[::2])

[10 20 30 40 50]
[20 30 40]
[10 20 30]
[10 30 50]


In [13]:
# Perform vectorized arithmetic operations

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [14]:
# Filter values using conditions

marks = np.array([45, 78, 92, 34, 67, 88])

print("Above 70:", marks[marks > 70])
print("Passed:", marks[marks >= 50])

Above 70: [78 92 88]
Passed: [78 92 67 88]


In [15]:
# Apply an operation to every array element

print("Original:", marks)
print("After adding 5:", marks + 5)

Original: [45 78 92 34 67 88]
After adding 5: [50 83 97 39 72 93]


In [17]:
# Calculate basic statistics
print("Original:", marks)
print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Standard Deviation:", np.std(marks))

Original: [45 78 92 34 67 88]
Sum: 404
Mean: 67.33333333333333
Median: 72.5
Minimum: 34
Maximum: 92
Standard Deviation: 21.445020141955776


In [18]:
# Find positions of maximum and minimum values

print("Maximum index:", np.argmax(marks))
print("Minimum index:", np.argmin(marks))

Maximum index: 2
Minimum index: 3


In [19]:
# Change the shape of an array

numbers = np.arange(1, 13)

matrix = numbers.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# Flatten and transpose a matrix

print("Flatten:")
print(matrix.flatten())

print("\nTranspose:")
print(matrix.T)

Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Transpose:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [21]:
# Perform calculations row-wise and column-wise

print("Column Sum:", np.sum(matrix, axis=0))
print("Row Sum:", np.sum(matrix, axis=1))
print("Row Mean:", np.mean(matrix, axis=1))

Column Sum: [15 18 21 24]
Row Sum: [10 26 42]
Row Mean: [ 2.5  6.5 10.5]


In [22]:
# Generate random student marks

np.random.seed(42)

data = np.random.randint(40, 101, (10, 5))

print(data)

[[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]]
