In [1]:
#task 1-Create a NumPy Array from 1 to 50
# Import NumPy
import numpy as np

# Create an array from 1 to 50
arr = np.arange(1, 51)

# Display the array
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [2]:
#task 2 -Find the Sum and Average
# Calculate the sum
print("Sum:", np.sum(arr))

# Calculate the average
print("Average:", np.mean(arr))

Sum: 1275
Average: 25.5


In [3]:
#task 3 -Reshape into a 5 × 10 Matrix
# Reshape the array into 5 rows and 10 columns
matrix = arr.reshape(5, 10)

# Display the matrix
print(matrix)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [5]:
#task  4 – Generate 15 Random Numbers
# Generate 15 random integers between 1 and 100
random_numbers = np.random.randint(1, 101, 15)

# Display the random numbers
print(random_numbers)

[85 81  6 24 11 72 71 28 48 93 95 55 68  1 10]


In [6]:
#task 5 – Sort the Array
# Sort the random numbers
sorted_array = np.sort(random_numbers)

# Display the sorted array
print(sorted_array)

[ 1  6 10 11 24 28 48 55 68 71 72 81 85 93 95]


In [7]:
#task 6 – Find Unique Values
# Create an array with duplicate values
numbers = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6, 7])

# Find unique values
unique_values = np.unique(numbers)

# Display unique values
print(unique_values)

[1 2 3 4 5 6 7]


In [8]:
#task 7 – Stack Two Arrays
# Create two arrays
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

# Stack the arrays vertically
stacked = np.vstack((a, b))

# Display the stacked array
print(stacked)


[[1 2 3]
 [4 5 6]]


In [9]:

#task 8 – Split an Array into 5 Parts
# Create an array
arr = np.arange(1, 26)

# Split the array into 5 equal parts
split_array = np.array_split(arr, 5)

# Display the split arrays
print(split_array)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20]), array([21, 22, 23, 24, 25])]


In [10]:
#task 9 – Calculate Standard Deviation
# Create an array
marks = np.array([80, 75, 90, 85, 95])

# Calculate standard deviation
std = np.std(marks)

# Display the result
print("Standard Deviation:", std)

Standard Deviation: 7.0710678118654755


In [11]:
#task 10 – Create an Identity Matrix of Size 5
# Create a 5 x 5 identity matrix
identity_matrix = np.eye(5)

# Display the identity matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
